[namelist:base_mesh]
f_lat_deg=45.0
fplane=.false.
geometry='planar'

[namelist:boundaries]
transport_overwrite_freq='split_step'

[namelist:external_forcing]
geostrophic_forcing=.true.

[namelist:extrusion]
domain_height=10.0e3
number_of_layers=38

[namelist:formulation]
l_multigrid=.false.
moisture_formulation='traditional'
moisture_in_solver=.true.
solver_moisture_conservation=.true.
theta_moist_source=.true.
use_physics=.true.
use_wavedynamics=.false.

[namelist:geostrophic_forcing]
profile_data_u=5.0
profile_data_v=3.0

[namelist:helmholtz_solver]
fail_on_non_converged=.true.
gcrk=18
method='bicgstab'
monitor_convergence=.true.
preconditioner='tridiagonal'
si_pressure_a_tol=1.0e-6

[namelist:idealised]
test='specified_profiles'

[namelist:initial_temperature]
profile_data=300.0,300.0
profile_heights=0.0,10.0e3
profile_size=2

[namelist:initial_vapour]
profile_data=0.0,0.0
profile_heights=0.0,10.0e3
profile_size=2

[namelist:initial_wind]
profile='constant_uv'
smp_init_wind=.true.

[namelist:io]
diagnostic_frequency=144

[!!namelist:multigrid]

[namelist:partitioning]
partitioner='planar'

[namelist:physics]
limit_drag_incs=.false.
sample_physics_scalars=.false.
sample_physics_winds=.false.

[namelist:section_choice]
aerosol='none'
boundary_layer='none'
chemistry='none'
cloud='none'
dynamics='none'
external_forcing=.true.
methane_oxidation=.false.
orographic_drag='none'
radiation='none'
spectral_gwd='none'
stochastic_physics='none'
surface='none'

[namelist:transport]
adjust_vhv_wind=.false.
ffsl_unity_3d=.false.
horizontal_method=2,2,1,2
panel_edge_treatment='none'
