[file:iodef.xml]
source=$ROSE_SUITE_DIR/app/jedi_forecast/file/iodef_gal_nwp_cycling.xml

[namelist:files]
iau_path='$BIG_DATA_DIR/start_dumps/basic-gal/yak/20210324T0600Z_um2lfric_iau_000001'
sea_ice_ancil_path='$BIG_DATA_DIR/start_dumps/basic-gal/yak/glu_ice'
snow_analysis_ancil_path='$BIG_DATA_DIR/start_dumps/basic-gal/yak/20210324T0600Z_glu_snow_um2lfric_fixed'
sst_ancil_path='$BIG_DATA_DIR/start_dumps/basic-gal/yak/sst_ugrid_postqa_fixed'
start_dump_directory='$BIG_DATA_DIR/start_dumps/basic-gal/yak/PR202'
start_dump_filename='20210324T0000Z_lfric_ice_dust_t+3'

[namelist:iau]
iau_ainc_multifile=.false.
iau_mode='instantaneous'
iau_outerloop=.false.
iau_pc2=.true.
iau_tendency_ainc=.false.
iau_use_addinf=.false.
iau_use_bcorr=.false.
iau_use_level_one_temp=.false.
iau_wet_density=.true.

[namelist:initialization]
!!init_eos_height=100
!!init_exner_method='hydrostatic'
init_option='checkpoint_dump'
!!init_sort_theta=.true.
!!read_w2h_wind=.false.
sea_ice_source='surf'
snow_source='surf'
sst_source='surf'

[namelist:section_choice]
iau=.true.

[namelist:time]
calendar_origin='2021-03-24 06:00:00'
calendar_start='2021-03-24 03:00:00'
