import=jedi_common/vn3.2

[namelist:jedi_increment]
compulsory=true
description=JEDI-LFRIC emulator increment configuration
help=Configuration options for JEDI-LFRIC emulator increment object.
ns=namelist/JEDI-LFRIC-setup/jedi_increment
title=jedi_increment

[namelist:jedi_increment=inc_time]
compulsory=true
description=The validity date of the increment
help=Format: yyyy-mm-dd hh:mm:ss
!kind=default
sort-key=
type=character

[namelist:jedi_increment=variables]
compulsory=true
description=List of variables to be instantiated
help=Add a comma separted list of variables to instantiate
    =format: 'theta', 'rho', ...
length=:
sort-key=
type=character
