##############################################################################
# (c) Crown copyright Met Office. All rights reserved.
# The file LICENCE, distributed with this code, contains details of the terms
# under which the code may be used.
##############################################################################

[check]

file-extensions= ["f90", "F90", "X90", "x90", "pf"]   #check these file types

select = ["E000", "C001", "C021", "C022", "C032", "C043",
"C051", "C061", "C071", "C072", "C091", "C092",
"C132", "C141", "OB011", "OB021", "OB051", "OB061", "MOD001", "MOD021",
"S101", "S071", "PORT011", "PORT012", "PORT021", "FORT001",
"FORT002", "FORT003", "FORT004", "FORT005"]


output-format = "grouped"                #group results by file

# Leaving out for now (these rules are used in the universal config):
# C081, E001, C121

[check.per-file-ignores]
# science/linear
"tl_ffsl_flux_xy_kernel_mod_test.pf" = ["C001"]
"tl_ffsl_flux_xy_sphere_kernel_mod_test.pf" = ["C001"]



