[command]
default=mkdir -p $MESH_DIR ; mpiexec -n 1 $BIN_DIR/planar_mesh_generator mesh_generation.nml

[env]
mesh_generator=Planar

[!!namelist:cubedsphere_mesh]

[namelist:mesh]
rotate_mesh=.true.
topology='non_periodic'

[namelist:planar_mesh]
domain_centre=1.2,-1.2
edge_cells_x=64
edge_cells_y=64
periodic_x=.false.
periodic_y=.false.
stretch_function='inflation'

[namelist:rotation]
target_north_pole=177.5,37.5

[namelist:stretch_transform]
cell_size_inner=0.0135,0.0135
cell_size_outer=0.036,0.036
n_cells_outer=5,5
n_cells_stretch=18,18
stretching_on='cell_centres'
