[command]
default=mkdir -p $MESH_DIR ; mpiexec -n 1 $BIN_DIR/planar_mesh_generator mesh_generation.nml

[env]
mesh_generator=Planar

[!!namelist:cubedsphere_mesh]

[namelist:mesh]
mesh_maps='dynamics:multigrid_l1','multigrid_l1:multigrid_l2',
         ='multigrid_l2:multigrid_l3','dynamics:multigrid_l3'
mesh_names='dynamics','multigrid_l1','multigrid_l2','multigrid_l3'
n_meshes=4
rotate_mesh=.true.
topology='non_periodic'

[namelist:planar_mesh]
domain_centre=-0.872500,1.6968
domain_size=1,1
edge_cells_x=960,480,240,120
edge_cells_y=1024,512,256,128
periodic_x=.false.
periodic_y=.false.
stretch_function='inflation'

[namelist:rotation]
target_north_pole=177.5,37.5

[namelist:stretch_transform]
cell_size_inner=0.0135,0.0135
cell_size_outer=0.036,0.036
n_cells_outer=140,85
n_cells_stretch=21,21
stretching_on='p_points'
