[namelist:lfric2lfric]
destination_mesh_name='dynamics'
destination_meshfile_prefix='${MESH_DIR}/seuk_MG/mesh_seuk_MG'
destination_topology='non_periodic'
target_domain='LAM'

[namelist:partitioning(destination)]
partitioner='planar'
