##############################################################################
# (c) Crown copyright Met Office. All rights reserved.
# The file LICENCE, distributed with this code, contains details of the terms
# under which the code may be used.
##############################################################################

[check]

file-extensions= ["f90", "F90", "X90", "x90", "pf"]  #check these file types

select = ["E000", "C001", "C021", "C022",
"C061", "C071", "C072", "C091", "C092",
"C132", "C141", "OB011", "OB021", "OB051", "OB061", "MOD001", "MOD021",
"S101", "S071", "PORT011", "PORT012", "PORT021", "FORT001",
"FORT002", "FORT003", "FORT004", "FORT005"]

output-format = "grouped"                #group results by file

[check.per-file-ignores]

"jedi_lfric_field_meta_mod.f90" = ["C061"]
"jedi_lfric_wind_fields_mod.f90" = ["C061"]
"atlas_field_interface_test.pf" = ["C021", "C031"]
"jedi_lfric_mesh_setup_mod.F90" = ["C072"]
"test_jedi_lfric_time_driver_mod.f90" = ["C072"]
"jedi_lfric_datetime_functions_mod_test.pf" = ["C001"]
"test_jedi_lfric_duration_mod.f90" = ["C072"]
"jedi_lfric_io_update_mod.f90" = ["C082"]
"jedi_lfric_io_update_test.pf" = ["C082"]
"jedi_lfric_utils_test.pf" = ["C082"]
"linear_state_trajectory_test.pf" = ["C082"]
"trajectory_field_utils_test.pf" = ["C082"]
"zero_field_collection_mod_test.pf" = ["C082"]

# Leaving out for now (these rules are used in the universal config):
# C081, E001

