[command]
default=$CORE_ROOT_DIR/bin/tweak_iodef; \
       =$LAUNCH_SCRIPT/launch-exe

[env]
ENSEMBLE_MEMBER=0
EXEC_NAME=lfric2um
EXTRA_NAMELIST_FILES=lfric2um.ctl configuration.nml io.nl
OMP_NUM_THREADS=1
RUN_METHOD=mpiexec
XIOS_SERVER_MODE=False

[file:configuration.nml]
source=namelist:base_mesh
      =namelist:extrusion
      =namelist:finite_element
      =namelist:io
      =namelist:planet
      =namelist:partitioning
      =namelist:formulation
      =namelist:logging
      =namelist:time

[file:input_mesh_faces.nc]
source=$LFRIC_MESH_FILE

[file:io.nl]
source=namelist:iofiles

[file:lfric2um.ctl]
source=namelist:configure_lfric2um namelist:regrid_options

[file:lfric2um_dump.nc]
source=$SOURCE_DUMP

[file:um_grid.nml]
source=$WEIGHT_LOC/um_grid.nml

[file:weights_file_face_centre_to_p_bilinear.nc]
source=$WEIGHT_LOC/FACE_CENTRE_to_P_bilinear.nc

[file:weights_file_face_centre_to_p_neareststod.nc]
source=$WEIGHT_LOC/FACE_CENTRE_to_P_neareststod.nc

[file:weights_file_face_centre_to_u_bilinear.nc]
source=$WEIGHT_LOC/FACE_CENTRE_to_U_bilinear.nc

[file:weights_file_face_centre_to_v_bilinear.nc]
source=$WEIGHT_LOC/FACE_CENTRE_to_V_bilinear.nc

[namelist:base_mesh]
f_lat_deg=45.0
file_prefix='input_mesh_faces'
fplane=.false.
geometry='spherical'
prepartitioned=.false.
prime_mesh_name='$LFRIC_MESH_NAME'
topology='fully_periodic'

[namelist:configure_lfric2um]
dump_validity_time=2012,12,10,9,0,0
lbproc_list=17*0
lbtim_list=17*1
output_filename='output.dump'
stash_list=2,3,150,4,389,391,392,393,394,265,266,267,268,25,26,24,60
stashmaster_file='$UMDIR/vn13.7/ctldata/STASHmaster/STASHmaster_A'
target_grid_namelist='um_grid.nml'
um_version_int=1105
weights_file_face_centre_to_p_bilinear='weights_file_face_centre_to_p_bilinear.nc'
weights_file_face_centre_to_p_neareststod='weights_file_face_centre_to_p_neareststod.nc'
weights_file_face_centre_to_u_bilinear='weights_file_face_centre_to_u_bilinear.nc'
weights_file_face_centre_to_v_bilinear='weights_file_face_centre_to_v_bilinear.nc'

[namelist:extrusion]
domain_height=39254.833575999997
method='um_L38_29t_9s_40km'
number_of_layers=$NUMBER_OF_LAYERS
planet_radius=6371229.0

[namelist:finite_element]
cellshape='quadrilateral'
coord_order=1
coord_order_nonprime=1
coord_space='Wchi'
coord_system='native'
element_order_h=0
element_order_v=0
rehabilitate=.true.
vorticity_in_w1=.true.

[namelist:formulation]
l_multigrid=.false.
use_multires_coupling=.false.
use_physics=.true.

[namelist:io]
checkpoint_read=.false.
checkpoint_write=.false.
counter_output_suffix='counter.txt'
diagnostic_frequency=1
file_convention='UGRID'
!!nodal_output_on_w3=.false.
subroutine_counters=.false.
subroutine_timers=.false.
timer_output_path='timer.txt'
use_xios_io=.true.
write_diag=.false.

[namelist:iofiles]
ancil_read=.false.
checkpoint_read=.true.
checkpoint_read_file='lfric2um_dump'
checkpoint_write=.false.

[namelist:logging]
run_log_level='info'

[namelist:partitioning]
generate_inner_halos=.true.
panel_decomposition='auto'
partitioner='cubedsphere'

[namelist:planet]
cp=1005.0
gravity=9.80665
omega=7.292116E-5
p_zero=100000.0
rd=287.05
scaling_factor=125.0

[namelist:regrid_options]
interp_method='bilinear'
regrid_type='global_to_global'
winds_on_w3=.true.

[namelist:time]
calendar='timestep'
calendar_origin='2016-01-01 15:00:00'
calendar_start='2016-01-01 15:00:00'
calendar_type='gregorian'
timestep_end=1
timestep_start=1
