[!!namelist:aerosol]
!!aclw_file='lut/nml_ac_lw'
!!acsw_file='lut/nml_ac_sw'
!!activation_scheme='off'
!!anlw_file='lut/nml_an_lw'
!!answ_file='lut/nml_an_sw'
!!crlw_file='lut/nml_cr_lw'
!!crsw_file='lut/nml_cr_sw'
!!horiz_d=2.25
!!l_radaer=.false.
!!n_radaer_step=1
!!prec_file='precalc/RADAER_pcalc.ukca'
!!sulphuric_strat_column=1.86604e-6
!!us_am=1.45

[!!namelist:cloud]
!!bm_ez_opt='subcrit'
!!cff_spread_rate=1.0e-5
!!dbsdtbs_turb_0=1.5E-4
!!ez_max=400.0
!!fsd_conv_const=2.81
!!fsd_min_conv_frac=0.0
!!fsd_nonconv_ice_const=1.14
!!fsd_nonconv_liq_const=1.14
!!ice_width=0.02
!!l_bm_sigma_s_grad=.false.
!!l_bm_tweaks=.false.
!!l_ensure_max_in_cloud_pc2=.false.
!!max_sigmas=3.0
!!min_sigx_ft=0.0
!!opt_depth_thresh=0.01
!!pc2_erosion_numerics='implicit'
!!pc2_homog_g_method='cf'
!!pc2_init_logic='original'
!!pc2_init_method='bimodal'
!!pc2_turb_horiz=.false.
!!turb_var_fac_bm=1.0

[namelist:convection]
!!c_mass_sh=0.03
!!cape_timescale=1800.0
!!cca_md_scaling=0.8
!!cpress_term=0.3
!!cv_scheme='gregory_rowntree'
!!efrac=1.0
!!ent_fac_sh=1.0
!!l_conv_prog_dq=.true.
!!l_conv_prog_dtheta=.true.
!!number_of_convection_substeps=2
!!orig_mdet_fac=1.0
!!prog_ent_grad=-1.1
!!prog_ent_int=-2.9
!!prog_ent_max=2.5
!!prog_ent_min=0.5
!!r_det=0.5
!!thpixs_mid=0.5

[namelist:files]
!!sea_ancil_path=''

[namelist:formulation]
moisture_formulation='dry'
!!moisture_in_solver=.true.
!!solver_moisture_conservation=.false.
!!theta_moist_source=.false.

[namelist:jules_radiation]
fixed_sea_albedo=0.3
i_sea_alb_method='fixed'
!!l_sea_alb_var_chl=.false.

[namelist:jules_sea_seaice]
beta_evap=0.0
hcap_sea=2.0e6
l_use_dtstar_sea=.true.

[!!namelist:microphysics]
!!a_ratio_exp=-0.2707
!!a_ratio_fac=0.0517
!!aut_qc=2.47
!!c_r_correl=0.9
!!ci_input=14.3
!!cic_input=1024.0
!!fcrit=1.0
!!graupel_scheme='none'
!!heavy_rain_evap_fac=0.0
!!l_mcr_precfrac=.false.
!!l_proc_fluxes=.false.
!!mp_dz_scal=2.0
!!nscalesf=1.0
!!nsigmasf=2.82843
!!orog_block=.true.
!!orog_rain=.false.
!!orog_rime=.true.
!!prog_tnuc=.false.
!!qcl_rime=1.0e-4
!!shape_rime=.true.

[namelist:physics]
!!convection_placement='fast'
!!microphysics_placement='slow'

[namelist:radiation]
!!cloud_inhomogeneity='mcica'
!!cloud_overlap='exponential_random'
cloud_representation='no_cloud'
!!cloud_vertical_decorr=10000.0
!!droplet_effective_radius='liu'
scatter_method_lw='none'

[namelist:radiative_gases]
h2o_rad_opt='off'

[namelist:section_choice]
!!aerosol='none'
!!cloud='none'
convection='none'
!!electric='none'
!!methane_oxidation=.false.
!!microphysics='um'
