[namelist:external_forcing]

[namelist:initial_temperature]
perturb='random'
theta_pert_end=7000.0
theta_pert_size=0.5
theta_pert_start=5000.0

[namelist:radiation]
n_radstep=15

[namelist:section_choice]
external_forcing=.true.
