[file:iodef.xml]
source=$ROSE_SUITE_DIR/app/lfric_atm/file/iodef_gal_nwp_coarse_nudging.xml

[namelist:external_forcing]
pc2_force_response=.false.
theta_forcing='nudging'
wind_forcing='nudging'

[namelist:files]
!!coarse_ancil_directory='$BIG_DATA_DIR/ancils/basic-gal/yak/C12'
nudging_directory='/data/users/mohit.dalvi/lfric/data/nudge/era/C12'
nudging_filename='era5_nudge_L137_C12_2021032400-2706'

[namelist:formulation]
use_multires_coupling=.true.

[namelist:multires_coupling]
aerosol_mesh_name='dynamics'
coarse_nudging=.true.
lowest_order_aero_flag=.false.
multires_coupling_mesh_tags='dynamics','multigrid_l2'
nudging_mesh_name='multigrid_l2'
orography_mesh_name='dynamics'
physics_mesh_name='dynamics'

[namelist:nudging]

[namelist:section_choice]
external_forcing=.true.
