[namelist:blayer]
kprof_cu='buoy_integ_low'
sc_diag_opt='cu_relax'

[namelist:cloud]
cff_spread_rate=1.0e-8
cloud_call_b4_conv=.true.
fsd_conv_const=3.0
fsd_min_conv_frac=0.02
fsd_nonconv_ice_const=0.8
fsd_nonconv_liq_const=0.8
pc2_homog_g_method='width'
pc2_init_logic='smooth'

[namelist:convection]
!!c_mass_sh=0.03
!!cape_timescale=1800.0
!!cca_md_scaling=0.8
!!cpress_term=0.3
cv_scheme='comorph'
!!efrac=1.0
!!ent_fac_sh=1.0
l_conv_prog_dq=.false.
l_conv_prog_dtheta=.false.
!!number_of_convection_substeps=2
!!orig_mdet_fac=1.0
par_gen_mass_fac=0.25
par_gen_rhpert=0.05
par_radius_ppn_max=3.5e-4
!!prog_ent_grad=-1.1
!!prog_ent_int=-2.9
!!prog_ent_max=2.5
!!prog_ent_min=0.5
!!r_det=0.5
resdep_precipramp=.false.
!!thpixs_mid=0.5

[namelist:jules_pftparm(brd_leaf)]
catch0_io=0.05
dcatch_dlai_io=0.27

[namelist:jules_pftparm(c3_grass)]
catch0_io=0.05
dcatch_dlai_io=0.73

[namelist:jules_pftparm(c4_grass)]
catch0_io=0.05
dcatch_dlai_io=0.71

[namelist:jules_pftparm(ndl_leaf)]
catch0_io=0.05
dcatch_dlai_io=0.44

[namelist:jules_pftparm(shrub)]
catch0_io=0.05
dcatch_dlai_io=1.0

[namelist:microphysics]
c_r_correl=0.7
ci_input=1.72e1
cic_input=1.23e3
graupel_scheme='modified'
l_improve_precfrac_checks=.false.
l_mcr_precfrac=.true.
update_precfrac_opt='homog'

[namelist:radiation]
liu_aparam=0.093
liu_bparam=-0.13
