[file:iodef.xml]
source=$ROSE_SUITE_DIR/app/lfric_atm/file/iodef_idealised.xml

[file:spec]
source=$SOURCE_ROOT/socrates-spectral/thai

[namelist:blayer]
bl_levels=37

[namelist:extrusion]
planet_radius=5797818.39

[namelist:files]
!!aerosols_ancil_path=''
ancil_directory=''
!!hydtop_ancil_path=''
!!land_area_ancil_path=''
!!orography_mean_ancil_path=''
!!orography_subgrid_ancil_path=''
!!ozone_ancil_path=''
!!plant_func_ancil_path=''
!!sea_ancil_path=''
!!sea_ice_ancil_path=''
!!soil_ancil_path=''
!!soil_dust_ancil_path=''
!!soil_rough_ancil_path='soil_roughness/prigent12/qrparm.soil_roughness'
!!sst_ancil_path=''
start_dump_directory=''
start_dump_filename=''
!!surface_frac_ancil_path=''

[namelist:idealised]
test='isot_dry_atm'

[namelist:initial_wind]
profile='none'
smp_init_wind=.false.

[namelist:initialization]
ancil_option='none'
!!init_eos_height=100
!!init_exner_method='hydrostatic'
init_option='analytic'
!!init_sort_theta=.true.
!!read_w2h_wind=.false.
!!sst_source='ancillary'

[namelist:jules_hydrology]
l_hydrology=.false.
!!l_var_rainfrac=.true.

[namelist:jules_radiation]
fixed_sea_albedo=0.06
i_sea_alb_method='fixed'
!!l_sea_alb_var_chl=.false.

[namelist:jules_sea_seaice]
emis_sea=1.0
hcap_sea=4.0e6
iseasurfalg='specified_roughness'
kappa_seasurf=2.5
l_use_dtstar_sea=.true.
z0h_specified=0.001
z0m_specified=0.01

[namelist:microphysics]
!!fcrit=1.0
!!nscalesf=1.0
!!nsigmasf=2.82843
!!orog_block=.false.
orog_rain=.false.
!!orog_rime=.false.

[namelist:orbit]
arg_periapsis=0.0
arg_periapsis_inc=0.0
eccentricity=0.0
eccentricity_inc=0.0
elements='user'
epoch=2451545.0
hour_angle=0.0
hour_angle_inc=0.0
mean_anomaly=0.0
mean_anomaly_inc=1.03003037823
obliquity=0.0
obliquity_inc=0.0
semimajor_axis=0.02928285
semimajor_axis_inc=0.0
spin='user'

[!!namelist:orographic_drag]

[namelist:orography]
orog_init_option='none'

[namelist:physics]
!!orographic_drag_placement='slow'
!!spectral_gwd_placement='slow'

[namelist:planet]
cp=1039.0
gravity=9.1201845
omega=1.19216478961e-5
rd=297.0

[namelist:radiation]
cloud_entrapment='max'
cloud_inhomogeneity='scaling'
i_cloud_ice_type_lw=8
i_cloud_ice_type_sw=8
l_trans_zen_correction=.false.
scatter_method_lw='full'
spectral_file_lw='spec/sp_lw_12_dsa'
spectral_file_sw='spec/sp_sw_21_dsa_trappist1'
topography='flat'

[namelist:radiative_gases]
!!cfc11_mix_ratio=1.110e-09
cfc11_rad_opt='off'
!!cfc12_mix_ratio=2.187e-09
cfc12_rad_opt='off'
!!ch4_mix_ratio=1.006e-06
ch4_rad_opt='off'
co2_mix_ratio=6.285e-04
n2_mix_ratio=0.9994
n2_rad_opt='constant'
!!n2o_mix_ratio=4.945e-07
n2o_rad_opt='off'
!!o2_mix_ratio=0.2314
o2_rad_opt='off'
o3_rad_opt='off'

[namelist:section_choice]
methane_oxidation=.false.
orographic_drag='none'
spectral_gwd='none'

[!!namelist:spectral_gwd]
!!cgw_scale_factor=1.05

[namelist:star]
stellar_constant=0.77173677371
stellar_radius=8.13969e7
