[namelist:base_mesh]
!!f_lat_deg=
!!fplane=
topology='non_periodic'

[namelist:boundaries]
blend_frequency='inner'
blending_weights=7*1.0,0.8,0.6,0.2
blending_weights_w2v=7*1.0,0.8,0.6,0.2
lbc_bal_meth='keep_rho'
lbc_eos_height=10
lbc_method='onion_layer'
lbc_sort_theta=.true.
limited_area=.true.
normal_only=.true.
output_lbcs=.true.
solver_boundary_depth=4
transport_boundary_depth=7

[namelist:initialization]
init_eos_height=38
read_w2h_wind=.true.
sst_source='start_dump'

[namelist:partitioning]
partitioner='planar'

[namelist:transport]
panel_edge_treatment='none'
