[namelist:cloud]
pc2_homog_g_method='width'

[namelist:convection]
!!c_mass_sh=0.03
!!cape_timescale=1800.0
!!cca_md_scaling=0.8
!!cpress_term=0.3
cv_scheme='comorph'
dx_ref=50000.0
!!efrac=1.0
!!ent_fac_sh=1.0
l_conv_prog_dq=.false.
l_conv_prog_dtheta=.false.
!!number_of_convection_substeps=2
!!orig_mdet_fac=1.0
par_gen_mass_fac=0.12
par_gen_rhpert=0.01
par_radius_ppn_max=3.5e-4
!!prog_ent_grad=-1.1
!!prog_ent_int=-2.9
!!prog_ent_max=2.5
!!prog_ent_min=0.5
!!r_det=0.5
resdep_precipramp=.true.
!!thpixs_mid=0.5

[namelist:microphysics]
heavy_rain_evap_fac=5.0e7
