[namelist:blayer]
bl_res_inv='off'

[!!namelist:cloud]
!!bm_ez_opt='subcrit'
!!cff_spread_rate=1.0e-5
!!dbsdtbs_turb_0=1.5E-4
!!ez_max=400.0
!!fsd_conv_const=2.81
!!fsd_min_conv_frac=0.0
!!fsd_nonconv_ice_const=1.14
!!fsd_nonconv_liq_const=1.14
!!ice_width=0.02
!!l_bm_sigma_s_grad=.false.
!!l_bm_tweaks=.false.
!!l_ensure_max_in_cloud_pc2=.false.
!!max_sigmas=3.0
!!min_sigx_ft=0.0
!!opt_depth_thresh=0.01
!!pc2_erosion_numerics='implicit'
!!pc2_homog_g_method='cf'
!!pc2_init_logic='original'
!!pc2_init_method='bimodal'
!!pc2_turb_horiz=.false.
!!turb_var_fac_bm=1.0

[namelist:convection]
!!c_mass_sh=0.03
!!cape_timescale=1800.0
!!cca_md_scaling=0.8
!!cpress_term=0.3
cv_scheme='lambert_lewis'
!!efrac=1.0
!!ent_fac_sh=1.0
!!l_conv_prog_dq=.true.
!!l_conv_prog_dtheta=.true.
!!number_of_convection_substeps=2
!!orig_mdet_fac=1.0
!!prog_ent_grad=-1.1
!!prog_ent_int=-2.9
!!prog_ent_max=2.5
!!prog_ent_min=0.5
!!r_det=0.5
!!thpixs_mid=0.5

[!!namelist:microphysics]
!!a_ratio_exp=-0.2707
!!a_ratio_fac=0.0517
!!aut_qc=2.47
!!c_r_correl=0.9
!!ci_input=14.3
!!cic_input=1024.0
!!fcrit=1.0
!!graupel_scheme='none'
!!heavy_rain_evap_fac=0.0
!!l_mcr_precfrac=.false.
!!l_proc_fluxes=.false.
!!mp_dz_scal=2.0
!!nscalesf=1.0
!!nsigmasf=2.82843
!!orog_block=.false.
!!orog_rain=.true.
!!orog_rime=.false.
!!prog_tnuc=.false.
!!qcl_rime=1.0e-4
!!shape_rime=.true.
turb_gen_mixph=.false.

[!!namelist:orbit]

[namelist:physics]
!!microphysics_placement='slow'
!!radiation_placement='slow'
!!spectral_gwd_placement='slow'

[!!namelist:radiation]
!!cloud_inhomogeneity='mcica'
!!cloud_overlap='exponential_random'
!!cloud_vertical_decorr=10000.0
!!droplet_effective_radius='liu'
!!liu_aparam=0.07
!!liu_bparam=-0.14

[namelist:section_choice]
cloud='none'
!!electric='none'
!!microphysics='none'
radiation='none'
spectral_gwd='none'

[!!namelist:spectral_gwd]
!!cgw_scale_factor=1.05

[!!namelist:star]
