[namelist:blayer]
noice_in_turb=.true.

[namelist:microphysics]
!!aut_qc=2.47
!!c_r_correl=0.9
casim_cdnc_opt='external'
!!ci_input=14.3
!!cic_input=1024.0
!!fcrit=1.0
!!graupel_scheme='modified'
!!heavy_rain_evap_fac=0.0
!!l_mcr_precfrac=.false.
!!l_proc_fluxes=.false.
microphysics_casim=.true.
!!nscalesf=1.0
!!nsigmasf=2.82843
!!orog_block=.false.
!!orog_rain=.false.
!!orog_rime=.false.
!!prog_tnuc=.false.
!!shape_rime=.true.

[namelist:radiation]
i_cloud_ice_type_lw=13
i_cloud_ice_type_sw=13
