[file:iodef.xml]
source=$ROSE_SUITE_DIR/app/lfric_atm/file/iodef_gal_nwp_nudging.xml

[namelist:external_forcing]
pc2_force_response=.false.
theta_forcing='nudging'
wind_forcing='nudging'

[namelist:files]
nudging_directory='/data/users/mohit.dalvi/lfric/data/nudge/era/C48'
nudging_filename='era5_nudge_L137_C48_MG_2021032400-2706'

[!!namelist:multires_coupling]
aerosol_mesh_name='dynamics'
coarse_nudging=.false.
!!nudging_mesh_name='dynamics'
orography_mesh_name='dynamics'
physics_mesh_name='dynamics'

[namelist:nudging]

[namelist:section_choice]
external_forcing=.true.
