[namelist:files]
ancil_directory='$BIG_DATA_DIR/ancils/basic-gc/Ticket3810/C48'
start_dump_directory='$BIG_DATA_DIR/start_dumps/basic-gc/Ticket3810'
start_dump_filename='cf652a.da19880101_00_UM2LFRIC'

[namelist:ideal_surface]
n_snow_layers=15*0
snow_depth=15*0.0
surf_tile_fracs=9*0.0,1.0,5*0.0
surf_tile_temps=9*295.0,300.0,5*265.0
tile_snow_mass=15*0.0

[namelist:initialization]
sea_ice_source='start_dump'

[namelist:jules_hydrology]
l_inland=.true.

[namelist:jules_sea_seaice]
nice=5

[namelist:surface]
check_soilm_negatives=.true.
lake_water_conservation=.true.

[namelist:time]
calendar_origin='1979-01-01 00:00:00'
calendar_start='1979-01-01 00:00:00'
