[namelist:blayer]
dzrad_disc_opt='smooth_1p5'
entr_smooth_dec='taper_zh'
free_atm_mix='smooth_to_boundaries'
improved_tke_diag=.true.
kprof_cu='buoy_integ_low'
l_converge_ga=.true.
l_use_sml_dsc_fixes=.true.
num_sweeps_bflux=6
sc_diag_opt='all_rh_max'

[namelist:cloud]
bm_ez_opt='entpar'
cff_spread_rate=1.0e-8
cloud_call_b4_conv=.true.
cloud_pc2_tol=1.0e-12
cloud_pc2_tol_2=1.0e-12
dbsdtbs_turb_0=3.0e-5
ent_coef_bm=0.2
fsd_conv_const=3.0
fsd_min_conv_frac=0.02
fsd_nonconv_ice_const=0.8
fsd_nonconv_liq_const=0.8
l_bm_sigma_s_grad=.true.
l_bm_tweaks=.true.
l_ensure_max_in_cloud_pc2=.true.
max_sigmas=2.0
min_sigx_ft=0.15
pc2_erosion_numerics='analytic'
pc2_homog_g_method='rev'
pc2_init_logic='smooth_fix'
pc2_turb_horiz=.true.
turb_var_fac_bm=4.0

[namelist:convection]
!!c_mass_sh=0.03
!!cape_timescale=1800.0
!!cca_md_scaling=0.8
!!cpress_term=0.3
cv_scheme='comorph'
!!efrac=1.0
!!ent_fac_sh=1.0
l_conv_prog_dq=.false.
l_conv_prog_dtheta=.false.
l_cvdiag_ctop_qmax=.true.
!!number_of_convection_substeps=2
!!orig_mdet_fac=1.0
par_gen_mass_fac=0.25
par_gen_rhpert=0.05
par_radius_ppn_max=3.5e-4
!!prog_ent_grad=-1.1
!!prog_ent_int=-2.9
!!prog_ent_max=2.5
!!prog_ent_min=0.5
!!r_det=0.5
resdep_precipramp=.false.
!!thpixs_mid=0.5

[namelist:jules_pftparm(brd_leaf)]
catch0_io=0.05
dcatch_dlai_io=0.27

[namelist:jules_pftparm(c3_grass)]
catch0_io=0.05
dcatch_dlai_io=0.73

[namelist:jules_pftparm(c4_grass)]
catch0_io=0.05
dcatch_dlai_io=0.71

[namelist:jules_pftparm(ndl_leaf)]
catch0_io=0.05
dcatch_dlai_io=0.44

[namelist:jules_pftparm(shrub)]
catch0_io=0.05
dcatch_dlai_io=1.0

[namelist:microphysics]
c_r_correl=0.7
ci_input=1.72e1
cic_input=1.23e3
graupel_scheme='modified'
heavy_rain_evap_fac=2.5e7
l_improve_precfrac_checks=.true.
l_mcr_precfrac=.true.
l_proc_fluxes=.true.
update_precfrac_opt='correl'

[namelist:mixing]
conservative_diffusion=.true.
density_weighted=.true.
fullstress=.false.
max_diff_factor=1.0
method='2d_smag'
mix_factor=0.2
smag_l_calc='UseDx'
smagorinsky=.true.

[namelist:physics]
smagorinsky_placement='fast'

[namelist:radiation]
liu_aparam=0.093
liu_bparam=-0.13
