##############################################################################
# (c) Crown copyright Met Office. All rights reserved.
# The file LICENCE, distributed with this code, contains details of the terms
# under which the code may be used.
##############################################################################

[check]

file-extensions= ["f90", "F90", "X90", "x90", "pf"]   #check these file types

select = ["E000", "E001", "C001",
"C071", "C072", "C081", "C091", "C092", "C121",
"C132", "C141", "OB011", "OB021", "OB051", "OB061", "MOD001", "MOD021",
"S101", "S071", "PORT011", "PORT012", "PORT021", "FORT001",
"FORT002", "FORT003", "FORT004", "FORT005"]



output-format = "grouped"                #group results by file

[check.per-file-ignores]
"stochastic_physics_run_mod.F90" = ["E001"]
"grow_particles_mod.F90" = ["C081"]
"mphys_die.F90" = ["C081"]
"dust_parameters_mod.F90" = ["C031"]
"diags_super_type_mod.F90" = ["C031"]
"init_diag_array.F90" = ["C031"]
"standalone_test.F90" = ["C031", "C043"]
"test_calc_cond_properties.F90" = ["C032", "C043"]
"test_moist_proc.F90" = ["C032", "C043"]
"downd-downd6a.F90" = ["C031"]
"tcs_parameters_warm.F90" = ["C031"]
"gw_ussp_core_mod.F90" = ["C051"]
"lsp_prognostic_tnuc.F90" = ["C031"]
"lsprec_mod.F90" = ["C031"]
"mphys_constants_mod.F90" = ["C031"]
"rad_input_mod.F90" = ["C031"]

# Leaving out for now (these rules are used in the universal config):
# C021, C022, C061



