import=lfric-linear/HEAD

[namelist:adjoint]
compulsory=true
description=Provides extra information for the adjoint model.
help=
ns=namelist/Adjoint
sort-key=Section-A07
title=Adjoint

[namelist:adjoint=l_compute_annexed_dofs]
compulsory=true
description=Boolean to control whether to loop into annexed dofs or not. MUST be false in the adjoint_tests app, otherwise true.
help=If true then loop into annexed dofs in PSyKAl lite code, else only loop into owned dofs and set halo dirty
!kind=default
ns=namelist/Adjoint/Testing
type=logical
