##############################################################################
# (c) Crown copyright Met Office. All rights reserved.
# The file LICENCE, distributed with this code, contains details of the terms
# under which the code may be used.
##############################################################################

[check]

file-extensions= ["f90", "F90", "X90", "x90", "pf"]   #check these file types

select = [
"E000", # io-error,
"E001", # syntax-error
"C001", # missing implicit none
"C021", # real literal missing kind suffix
"C022", # implicit-real-kind
"C061", # missing-intent
"C071", # assumed-size variables
"C072", # character has assumed size but does not have intent(in)
"C081", # initialisation-in-declaration and no explicit save/parameter
"C091", # external-procedure
"C092", # procedure not contained within module
"C121", # use-all - use missing "only" clause
"C132", # default-public-accessibility
"C141", # missing-exit-or-cycle-label
"OB011", # common-block, obsolescent
"OB021", # entry-statement, obsolescent
"OB051", # pause-statement, deleted feature
"OB061", # deprecated-character-syntax
"MOD001", # don't use double-precision
"MOD021", # deprecated-relational-operator
"S101", # trailing-whitespace
"S071", # missing-double-colon
"PORT011", # literal-kind
"PORT012", # literal-kind-suffix
"PORT021", # star-kind, non-standard syntax
"FORT001", # invalid-rule-code-or-name
"FORT002", # unused-allow-comment
"FORT003", # redirected-allow-comment
"FORT004", # duplicated-allow-comment
"FORT005"] # disabled-allow-comment


output-format = "grouped"                #group results by file

# Repos with too many errors with the above rules have their own toml files.

# Repos containing only a few files with errors for the above rules
# are dealt with below:

[check.per-file-ignores] #don't run these rules on these files:

# transport files:
"analytic_tracer_field_profiles_mod_test.pf" = ["E001", "C121"]
"set_tracer_field_kernel_mod_test.pf" = ["E001", "C121"]
"initial_tracer_field_sample_kernel_mod_test.pf" = ["E001", "C121"]
"divergence_alg_mod.x90" = ["C082"]
"mass_conservation_alg_mod.x90" = ["C082"]
"transport_init_fields_alg_mod.x90" = ["C082"]
"transport_mod.f90" = ["C031"]
"initial_tracer_field_sample_kernel_mod.F90" = ["C031"]
"set_tracer_field_kernel_mod.F90" = ["C031"]

# name_transport files:
"analytic_name_field_profiles_mod_test.pf" = ["E001", "C121"]
"set_name_field_kernel_mod_test.pf" = ["E001", "C121"]
"name_transport_init_fields_alg_mod.x90" = ["C082"]
"name_transport_mod.f90" = ["C031"]

# ngarch files:
"ngarch_mod.f90" = ["C031"]
"override_timestep_mod.f90" = ["C082"]

# lfric2lfric files:
"lfric2lfric_mod.f90" = ["C031"]
"lfric2lfric_init_coupler_mod.F90" = ["C082"]
"lfric2lfric_init_mesh.f90" = ["C082"]

# gravity_wave files:
"analytic_buoyancy_profiles_mod_test.pf" = ["E001", "C121"]
"compute_q_operator_kernel_mod_test.pf" = ["E001", "C121", "C031", "C081"]
"initial_buoyancy_kernel_mod_test.pf" = ["E001", "C121"]
"gravity_wave_alg_mod.x90" = ["C082"]
"gw_mixed_diag_precon_alg_mod.x90" = ["C082"]
"gw_mixed_operator_alg_mod.x90" = ["C082"]
"gw_mixed_schur_precon_alg_mod.x90" = ["C082"]
"gw_pressure_operator_alg_mod.x90" = ["C082"]
"gw_pressure_precon_alg_mod.x90" = ["C082"]
"gravity_wave_infrastructure_mod.f90" = ["C082"]
"gravity_wave_mod.f90" = ["C031"]

# solver files:
"solver_miniapp_mod.f90" = ["C031"]

# science/shared:
"space_from_metadata_mod.F90" = ["C072"]
"space_from_metadata_mod_test.pf" = ["E001","C121", "C081"]
"lfric_apps_version_mod_test.pf" = ["E001", "C121", "C081"]

# science/socrates_interface:
"init_radiation_fields_alg_mod.x90" = ["C082"]
"rad_cloud_alg_mod.x90" = ["C082"]
"lw_kernel_mod.F90" = ["C031"]
"set_thermodynamic_kernel_mod_test.pf" = ["E001", "C121"]
"set_rad_cloud_kernel_mod_test.pf" = ["E001", "C121"]
"set_n_cloud_layer_kernel_mod_test.pf" = ["E001", "C121"]
"rand_seed_kernel_mod_test.pf" = ["E001", "C121"]
"set_topography_kernel_mod.F90" = ["C081", "C031"]
"cosp_alg_mod.x90" = ["C082"]
"illuminate_alg_mod.x90" = ["C082"]
"radiation_alg_mod.x90" = ["C082"]
"cosp_kernel_mod.f90" = ["C031"]
"illuminate_kernel_mod.F90" = ["C031"]
"lw_inc_kernel_mod.F90" = ["C031"]
"lw_mts_kernel_mod.F90" = ["C031"]
"rand_seed_kernel_mod.f90" = ["C031"]
"set_rad_cloud_kernel_mod.f90" = ["C031"]
"set_thermodynamic_kernel_mod.f90" = ["C031"]
"sw_inc_kernel_mod.F90" = ["C031"]
"sw_kernel_mod.F90" = ["C031"]
"sw_mts_kernel_mod.F90" = ["C031"]

# interfaces/coupled_interface:
"convert_to_celsius_kernel_mod_test.pf" = ["C121", "E001"]
"value_based_mask_kernel_mod_test.pf" = ["E001", "C121", "C031"]
"convert_to_marine_fraction_mod.F90" = ["C031"]
"process_o2a_kernel_mod.F90" = ["C031"]

# interfaces/jules_interface:
"jules_imp_alg_mod.x90" = ["C061","C082"]
"update_ancils_alg_mod.x90" = ["C082"]
"jules_exp_kernel_mod.F90" = ["C031"]
"jules_extra_kernel_mod.F90" = [ "C031"]
"jules_imp_kernel_mod.F90" = ["C031"]
"jules_control_init_mod.f90" = ["C081"]
"jules_physics_init_mod.f90" = ["C081"]
"init_snow_fields_alg_mod.x90" = ["C082"]
"init_soil_fields_alg_mod.x90" = ["C082"]
"init_surface_fields_alg_mod.x90" = ["C082"]
"jules_extra_alg_mod.x90" = ["C082"]
"jules_timestep_alg_mod.x90" = ["C082"]
"lake_water_correction_alg_mod.x90" = ["C082"]
"process_inputs_alg_mod.x90" = ["C082"]
"rad_tile_alg_mod.x90" = ["C082"]
"apply_lake_correction_kernel_mod.F90" = ["C031"]
"generate_moist_mask_kernel_mod.F90" = ["C031"]
"initial_snow_kernel_mod.F90" = ["C031"]
"initial_surface_kernel_mod.F90" = ["C031"]
"lw_rad_tile_kernel_mod.F90" = ["C031"]
"masked_process_ssi_kernel_mod.F90" = ["C031"]
"process_snow_kernel_mod.F90" = ["C031"]
"process_soil_kernel_mod.F90" = ["C031"]
"process_ssi_kernel_mod.F90" = ["C031"]
"process_urban_kernel_mod.F90" = ["C031"]
"sw_rad_tile_kernel_mod.F90" = ["C031"]


# applications/jedi_lfric_tests:
"jedi_lfric_tests_increment_alg_mod.x90" = ["C081"]
"test_algorithm_mod.x90" = ["C082"]
"jedi_lfric_tests_mod.f90" = ["C031"]
"jedi_checksum_mod.f90" = ["C082"]

# applications/adjoint_tests:
"atlt_poly_adv_update_alg_mod.X90" = ["C132"]
"atlt_bl_inc_alg_mod.x90" = ["C132", "C082"]
"atlt_bdy_lyr_alg_mod.x90" = ["C132"]
"atlt_rhs_alg_mod.x90" = ["C132"]
"atlt_pressure_gradient_bd_alg_mod.x90" = ["C132"]
"atlt_moist_dyn_factors_alg_mod.x90" = ["C132"]
"atlt_derive_exner_from_eos_alg_mod.x90" = ["C132"]
"adjt_compute_vorticity_alg_mod.x90" = ["C132"]
"atlt_moist_dyn_mass_alg_mod.x90" = ["C031"]
