[namelist:formulation]
moisture_formulation='dry'
!!moisture_in_solver=.false.
!!solver_moisture_conservation=.false.
!!theta_moist_source=.false.

[namelist:section_choice]
!!aerosol='none'
!!cloud='none'
!!methane_oxidation=.false.
